Added page specific JS (fix 37)
jaydenwindle/decode2017 pull request #60
Opened 2017-04-19 23:14 UTC by jaydenwindle

## Description

- Added auto loading of page-specific JS (e.g. when `giveaways#index` is loaded, `assets/javascripts/giveaways/index.js` gets included)
- moved dash_main.js and dash_submit.js to their respective page-specific js files

## Motivation and Context

Step in the right direction to fix #37, still need to remove the inline js in `giveaways/show.html.erb` and `giveaways/winners.html.erb`

## How Has This Been Tested?

Manual testing in dev env, all js functionality is still working

## Screenshots (if appropriate):
N/A
## Types of changes

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [guidelines](CONTRIBUTING.md) of this project.
- [  ] My change requires a change to the documentation.
- [  ] I have updated the documentation accordingly.

2017-04-19 23:19 UTC, karimsa requested changes
Other than the semicolons, it looks good.

Was there a way to add a wildcard in the rails config for manually removing files from the bundle? That way we won't have to remember to do that every time there's new JS.

2017-04-19 23:19 UTC, karimsa commented on app/assets/javascripts/dash_main.js
> +;
Semicolons are not needed in JS.

2017-04-19 23:19 UTC, karimsa commented on app/assets/javascripts/dash_submit.js
> +;
Semicolons are not needed in JS.

2017-04-20 18:06 UTC, jaydenwindle commented on app/assets/javascripts/dash_main.js
> +;
Sorry, bad habit. I learned JS circa 2009 so it's largely just muscle memory :stuck_out_tongue:

2017-04-20 18:07 UTC, jaydenwindle commented
I tried adding wildcards but couldn't get it to work for me. I'll add the files manually for now and then try to change it to wildcards later

2017-04-21 21:13 UTC, merged